//@generated
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protobuf/task.proto

package proto // import "github.com/yuwenhui/gin-starter/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GET /api/v1/tasks
type TaskResponse struct {
	Tasks                []*TaskItem `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_199896180c77aa3f, []int{0}
}
func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (dst *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(dst, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetTasks() []*TaskItem {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskResponse)(nil), "task.TaskResponse")
}

func init() { proto.RegisterFile("proto/protobuf/task.proto", fileDescriptor_task_199896180c77aa3f) }

var fileDescriptor_task_199896180c77aa3f = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0x49, 0xa5, 0x69, 0xfa, 0x25, 0x89, 0xc5, 0xd9, 0x7a, 0x60, 0x9e, 0x10,
	0x0b, 0x88, 0x2d, 0x25, 0x8d, 0xa6, 0x20, 0x39, 0x3f, 0x37, 0x37, 0x3f, 0x0f, 0xa2, 0x44, 0xc9,
	0x8c, 0x8b, 0x27, 0x24, 0xb1, 0x38, 0x3b, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48,
	0x8d, 0x8b, 0x15, 0xa4, 0xa9, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x40, 0x0f, 0xaa,
	0x1a, 0xa4, 0xc8, 0xb3, 0x24, 0x35, 0x37, 0x08, 0x22, 0xed, 0xa4, 0x1e, 0xa5, 0x9a, 0x9e, 0x59,
	0x92, 0x51, 0x9a, 0x04, 0x52, 0xa0, 0x5f, 0x59, 0x5a, 0x9e, 0x9a, 0x97, 0x51, 0x9a, 0xa9, 0x9f,
	0x9e, 0x99, 0xa7, 0x5b, 0x5c, 0x92, 0x58, 0x54, 0x92, 0x5a, 0x04, 0xb5, 0x90, 0x0d, 0x4c, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x34, 0x6c, 0x9d, 0xa7, 0x00, 0x00, 0x00,
}
